/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const Configuration = {
    // The base Uri for API calls
    BASEURI: 'http://localhost:8081/hr-fhir-api',

};

module.exports = Configuration;
