/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const AcceptUnknownEnum = {

    /**
     * TODO: Write general description for this element
     */
    NO: 'no',

    /**
     * TODO: Write general description for this element
     */
    EXTENSIONS: 'extensions',

    /**
     * TODO: Write general description for this element
     */
    ELEMENTS: 'elements',

    /**
     * TODO: Write general description for this element
     */
    BOTH: 'both',

};

module.exports = AcceptUnknownEnum;
