/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BackboneElement = require('./BackboneElement');

/**
 * Creates an instance of Animal
 */
class Animal extends BackboneElement {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.species = this.constructor.getValue(obj.species);
        this.breed = this.constructor.getValue(obj.breed);
        this.genderStatus = this.constructor.getValue(obj.genderStatus);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'species', realName: 'species', type: 'CodeableConcept' },
            { name: 'breed', realName: 'breed', type: 'CodeableConcept' },
            { name: 'genderStatus', realName: 'genderStatus', type: 'CodeableConcept' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = Animal;
