/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Element = require('./Element');

/**
 * Creates an instance of Attachment
 */
class Attachment extends Element {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.contentType = this.constructor.getValue(obj.contentType);
        this.language = this.constructor.getValue(obj.language);
        this.data = this.constructor.getValue(obj.data);
        this.url = this.constructor.getValue(obj.url);
        this.size = this.constructor.getValue(obj.size);
        this.hash = this.constructor.getValue(obj.hash);
        this.title = this.constructor.getValue(obj.title);
        this.creation = this.constructor.getValue(obj.creation);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'contentType', realName: 'contentType' },
            { name: 'language', realName: 'language' },
            { name: 'data', realName: 'data' },
            { name: 'url', realName: 'url' },
            { name: 'size', realName: 'size' },
            { name: 'hash', realName: 'hash' },
            { name: 'title', realName: 'title' },
            { name: 'creation', realName: 'creation', isDateTime: true, dateTimeValue: 'rfc3339' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = Attachment;
