/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CategoryEnum = {

    /**
     * TODO: Write general description for this element
     */
    CONSEQUENCE: 'Consequence',

    /**
     * TODO: Write general description for this element
     */
    CURRENCY: 'Currency',

    /**
     * TODO: Write general description for this element
     */
    NOTIFICATION: 'Notification',

};

module.exports = CategoryEnum;
