/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CategoryEnum382Enum = {

    /**
     * TODO: Write general description for this element
     */
    FOOD: 'food',

    /**
     * TODO: Write general description for this element
     */
    MEDICATION: 'medication',

    /**
     * TODO: Write general description for this element
     */
    ENVIRONMENT: 'environment',

    /**
     * TODO: Write general description for this element
     */
    OTHER: 'other',

};

module.exports = CategoryEnum382Enum;
