/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CertaintyEnum = {

    /**
     * TODO: Write general description for this element
     */
    UNLIKELY: 'unlikely',

    /**
     * TODO: Write general description for this element
     */
    LIKELY: 'likely',

    /**
     * TODO: Write general description for this element
     */
    CONFIRMED: 'confirmed',

};

module.exports = CertaintyEnum;
