/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ClinicalStatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    ACTIVE: 'active',

    /**
     * TODO: Write general description for this element
     */
    RELAPSE: 'relapse',

    /**
     * TODO: Write general description for this element
     */
    REMISSION: 'remission',

    /**
     * TODO: Write general description for this element
     */
    RESOLVED: 'resolved',

};

module.exports = ClinicalStatusEnum;
