/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CodeEnum132Enum = {

    /**
     * TODO: Write general description for this element
     */
    TRANSACTION: 'transaction',

    /**
     * TODO: Write general description for this element
     */
    SEARCHSYSTEM: 'search-system',

    /**
     * TODO: Write general description for this element
     */
    HISTORYSYSTEM: 'history-system',

};

module.exports = CodeEnum132Enum;
