/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CodeEnum = {

    /**
     * TODO: Write general description for this element
     */
    READ: 'read',

    /**
     * TODO: Write general description for this element
     */
    VREAD: 'vread',

    /**
     * TODO: Write general description for this element
     */
    UPDATE: 'update',

    /**
     * TODO: Write general description for this element
     */
    MDELETE: 'delete',

    /**
     * TODO: Write general description for this element
     */
    HISTORYINSTANCE: 'history-instance',

    /**
     * TODO: Write general description for this element
     */
    VALIDATE: 'validate',

    /**
     * TODO: Write general description for this element
     */
    HISTORYTYPE: 'history-type',

    /**
     * TODO: Write general description for this element
     */
    CREATE: 'create',

    /**
     * TODO: Write general description for this element
     */
    SEARCHTYPE: 'search-type',

};

module.exports = CodeEnum;
