/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CoditionalDeleteEnum = {

    /**
     * TODO: Write general description for this element
     */
    NOTSUPPORTED: 'not-supported',

    /**
     * TODO: Write general description for this element
     */
    SINGLE: 'single',

    /**
     * TODO: Write general description for this element
     */
    MULTIPLE: 'multiple',

};

module.exports = CoditionalDeleteEnum;
