/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ComparatorEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_LT: '<',

    /**
     * TODO: Write general description for this element
     */
    ENUM_LE: '<=',

    /**
     * TODO: Write general description for this element
     */
    ENUM_GE: '>=',

    /**
     * TODO: Write general description for this element
     */
    ENUM_GT: '>',

};

module.exports = ComparatorEnum;
