/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CriticalityEnum = {

    /**
     * TODO: Write general description for this element
     */
    CRITL: 'CRITL',

    /**
     * TODO: Write general description for this element
     */
    CRITH: 'CRITH',

    /**
     * TODO: Write general description for this element
     */
    CRITU: 'CRITU',

};

module.exports = CriticalityEnum;
