/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Resource = require('./Resource');

/**
 * Creates an instance of DomainResource
 */
class DomainResource extends Resource {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.resourceType = this.constructor.getValue(obj.resourceType);
        this.text = this.constructor.getValue(obj.text);
        this.contained = this.constructor.getValue(obj.contained);
        this.extension = this.constructor.getValue(obj.extension);
        this.modifierExtension = this.constructor.getValue(obj.modifierExtension);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'resourceType', realName: 'resourceType' },
            { name: 'text', realName: 'text', type: 'Narrative' },
            { name: 'contained', realName: 'contained', array: true, type: 'Resource' },
            { name: 'extension', realName: 'extension', array: true, type: 'Extension' },
            {
                name: 'modifierExtension',
                realName: 'modifierExtension',
                array: true,
                type: 'Extension',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = DomainResource;
