/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const DurationUnitsEnum = {

    /**
     * TODO: Write general description for this element
     */
    S: 's',

    /**
     * TODO: Write general description for this element
     */
    MIN: 'min',

    /**
     * TODO: Write general description for this element
     */
    H: 'h',

    /**
     * TODO: Write general description for this element
     */
    D: 'd',

    /**
     * TODO: Write general description for this element
     */
    WK: 'wk',

    /**
     * TODO: Write general description for this element
     */
    MO: 'mo',

    /**
     * TODO: Write general description for this element
     */
    A: 'a',

};

module.exports = DurationUnitsEnum;
