/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const EncounterStateEnum = {

    /**
     * TODO: Write general description for this element
     */
    PLANNED: 'planned',

    /**
     * TODO: Write general description for this element
     */
    ARRIVED: 'arrived',

    /**
     * TODO: Write general description for this element
     */
    INPROGRESS: 'in-progress',

    /**
     * TODO: Write general description for this element
     */
    ONLEAVE: 'onleave',

    /**
     * TODO: Write general description for this element
     */
    FINISHED: 'finished',

    /**
     * TODO: Write general description for this element
     */
    CANCELLED: 'cancelled',

};

module.exports = EncounterStateEnum;
