/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BackboneElement = require('./BackboneElement');

/**
 * Creates an instance of Entry
 */
class Entry extends BackboneElement {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.link = this.constructor.getValue(obj.link);
        this.fullUrl = this.constructor.getValue(obj.fullUrl);
        this.search = this.constructor.getValue(obj.search);
        this.request = this.constructor.getValue(obj.request);
        this.response = this.constructor.getValue(obj.response);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'link', realName: 'link', array: true, type: 'LinkItem' },
            { name: 'fullUrl', realName: 'fullUrl' },
            { name: 'search', realName: 'search', type: 'Search' },
            { name: 'request', realName: 'request', type: 'Request' },
            { name: 'response', realName: 'response', type: 'Response' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = Entry;
