/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const FormatEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_APPLICATIONJSON: 'application/json',

    /**
     * TODO: Write general description for this element
     */
    ENUM_APPLICATIONXML: 'application/xml',

};

module.exports = FormatEnum;
