/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const FormatItemEnum = {

    /**
     * TODO: Write general description for this element
     */
    XML: 'xml',

    /**
     * TODO: Write general description for this element
     */
    JSON: 'json',

    /**
     * TODO: Write general description for this element
     */
    ENUM_APPLICATIONXML: 'application/xml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_APPLICATIONJSON: 'application/json',

};

module.exports = FormatItemEnum;
