/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const GenderEnum = {

    /**
     * TODO: Write general description for this element
     */
    MALE: 'male',

    /**
     * TODO: Write general description for this element
     */
    FEMALE: 'female',

    /**
     * TODO: Write general description for this element
     */
    OTHER: 'other',

    /**
     * TODO: Write general description for this element
     */
    UNKNOWN: 'unknown',

};

module.exports = GenderEnum;
