/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const KindEnum = {

    /**
     * TODO: Write general description for this element
     */
    INSTANCE: 'instance',

    /**
     * TODO: Write general description for this element
     */
    CAPABILITY: 'capability',

    /**
     * TODO: Write general description for this element
     */
    REQUIREMENTS: 'requirements',

};

module.exports = KindEnum;
