/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BackboneElement = require('./BackboneElement');

/**
 * Creates an instance of MessagingItem
 */
class MessagingItem extends BackboneElement {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.documentation = this.constructor.getValue(obj.documentation);
        this.event = this.constructor.getValue(obj.event);
        this.endpoint = this.constructor.getValue(obj.endpoint);
        this.reliableCache = this.constructor.getValue(obj.reliableCache);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'documentation', realName: 'documentation' },
            { name: 'event', realName: 'event', array: true, type: 'EventItem' },
            { name: 'endpoint', realName: 'endpoint', array: true, type: 'EndpointItem' },
            { name: 'reliableCache', realName: 'reliableCache' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = MessagingItem;
