/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Element = require('./Element');

/**
 * Creates an instance of Meta
 */
class Meta extends Element {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.versionId = this.constructor.getValue(obj.versionId);
        this.lastUpdated = this.constructor.getValue(obj.lastUpdated);
        this.profile = this.constructor.getValue(obj.profile);
        this.security = this.constructor.getValue(obj.security);
        this.tag = this.constructor.getValue(obj.tag);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'versionId', realName: 'versionId' },
            { name: 'lastUpdated', realName: 'lastUpdated' },
            { name: 'profile', realName: 'profile' },
            { name: 'security', realName: 'security', array: true, type: 'Coding' },
            { name: 'tag', realName: 'tag', array: true, type: 'Coding' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = Meta;
