/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const MethodEnum = {

    /**
     * TODO: Write general description for this element
     */
    GET: 'GET',

    /**
     * TODO: Write general description for this element
     */
    PUT: 'PUT',

    /**
     * TODO: Write general description for this element
     */
    POST: 'POST',

    /**
     * TODO: Write general description for this element
     */
    MDELETE: 'DELETE',

};

module.exports = MethodEnum;
