/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ModeEnum164Enum = {

    /**
     * TODO: Write general description for this element
     */
    SENDER: 'sender',

    /**
     * TODO: Write general description for this element
     */
    RECEIVER: 'receiver',

};

module.exports = ModeEnum164Enum;
