/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ModeEnum176Enum = {

    /**
     * TODO: Write general description for this element
     */
    PRODUCER: 'producer',

    /**
     * TODO: Write general description for this element
     */
    CONSUMER: 'consumer',

};

module.exports = ModeEnum176Enum;
