/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ModeEnum = {

    /**
     * TODO: Write general description for this element
     */
    CLIENT: 'client',

    /**
     * TODO: Write general description for this element
     */
    SERVER: 'server',

};

module.exports = ModeEnum;
