/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ModeEnum890Enum = {

    /**
     * TODO: Write general description for this element
     */
    MATCH: 'match',

    /**
     * TODO: Write general description for this element
     */
    INCLUDE: 'include',

    /**
     * TODO: Write general description for this element
     */
    OUTCOME: 'outcome',

};

module.exports = ModeEnum890Enum;
