/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Element = require('./Element');

/**
 * Creates an instance of Quantity
 */
class Quantity extends Element {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.value = this.constructor.getValue(obj.value);
        this.comparator = this.constructor.getValue(obj.comparator);
        this.unit = this.constructor.getValue(obj.unit);
        this.system = this.constructor.getValue(obj.system);
        this.code = this.constructor.getValue(obj.code);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'value', realName: 'value' },
            { name: 'comparator', realName: 'comparator' },
            { name: 'unit', realName: 'unit' },
            { name: 'system', realName: 'system' },
            { name: 'code', realName: 'code' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = Quantity;
