/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const RequiredEnum = {

    /**
     * TODO: Write general description for this element
     */
    REQUIRED: 'required',

    /**
     * TODO: Write general description for this element
     */
    OPTIONAL: 'optional',

    /**
     * TODO: Write general description for this element
     */
    INFORMATIONONLY: 'information-only',

};

module.exports = RequiredEnum;
