/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BackboneElement = require('./BackboneElement');

/**
 * Creates an instance of SearchParamItem
 */
class SearchParamItem extends BackboneElement {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.type = this.constructor.getValue(obj.type);
        this.definition = this.constructor.getValue(obj.definition);
        this.documentation = this.constructor.getValue(obj.documentation);
        this.target = this.constructor.getValue(obj.target);
        this.chain = this.constructor.getValue(obj.chain);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'type', realName: 'type' },
            { name: 'definition', realName: 'definition' },
            { name: 'documentation', realName: 'documentation' },
            { name: 'target', realName: 'target', array: true },
            { name: 'chain', realName: 'chain', array: true },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = SearchParamItem;
