/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BackboneElement = require('./BackboneElement');

/**
 * Creates an instance of Security
 */
class Security extends BackboneElement {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.cors = this.constructor.getValue(obj.cors);
        this.service = this.constructor.getValue(obj.service);
        this.description = this.constructor.getValue(obj.description);
        this.certificate = this.constructor.getValue(obj.certificate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'cors', realName: 'cors' },
            { name: 'service', realName: 'service', array: true, type: 'CodeableConcept' },
            { name: 'description', realName: 'description' },
            { name: 'certificate', realName: 'certificate', array: true, type: 'CertificateItem' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = Security;
