/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const SeverityEnum = {

    /**
     * TODO: Write general description for this element
     */
    MILD: 'mild',

    /**
     * TODO: Write general description for this element
     */
    MODERATE: 'moderate',

    /**
     * TODO: Write general description for this element
     */
    SEVERE: 'severe',

};

module.exports = SeverityEnum;
