/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const StatusEnum337Enum = {

    /**
     * TODO: Write general description for this element
     */
    ACCEPTED: 'accepted',

    /**
     * TODO: Write general description for this element
     */
    DECLINED: 'declined',

    /**
     * TODO: Write general description for this element
     */
    TENTATIVE: 'tentative',

    /**
     * TODO: Write general description for this element
     */
    NEEDSACTION: 'needs-action',

};

module.exports = StatusEnum337Enum;
