/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const StatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    DRAFT: 'draft',

    /**
     * TODO: Write general description for this element
     */
    ACTIVE: 'active',

    /**
     * TODO: Write general description for this element
     */
    RETIRED: 'retired',

};

module.exports = StatusEnum;
