/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const StatusEnum379Enum = {

    /**
     * TODO: Write general description for this element
     */
    ACTIVE: 'active',

    /**
     * TODO: Write general description for this element
     */
    UNCONFIRMED: 'unconfirmed',

    /**
     * TODO: Write general description for this element
     */
    CONFIRMED: 'confirmed',

    /**
     * TODO: Write general description for this element
     */
    INACTIVE: 'inactive',

    /**
     * TODO: Write general description for this element
     */
    RESOLVED: 'resolved',

    /**
     * TODO: Write general description for this element
     */
    REFUTED: 'refuted',

    /**
     * TODO: Write general description for this element
     */
    ENTEREDINERROR: 'entered-in-error',

};

module.exports = StatusEnum379Enum;
