/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const StatusEnum521Enum = {

    /**
     * TODO: Write general description for this element
     */
    ACTIVE: 'active',

    /**
     * TODO: Write general description for this element
     */
    ONHOLD: 'on-hold',

    /**
     * TODO: Write general description for this element
     */
    COMPLETED: 'completed',

    /**
     * TODO: Write general description for this element
     */
    ENTEREDINERROR: 'entered-in-error',

    /**
     * TODO: Write general description for this element
     */
    STOPPED: 'stopped',

    /**
     * TODO: Write general description for this element
     */
    DRAFT: 'draft',

};

module.exports = StatusEnum521Enum;
