/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const StatusEnum312Enum = {

    /**
     * TODO: Write general description for this element
     */
    PROPOSED: 'proposed',

    /**
     * TODO: Write general description for this element
     */
    PENDING: 'pending',

    /**
     * TODO: Write general description for this element
     */
    BOOKED: 'booked',

    /**
     * TODO: Write general description for this element
     */
    ARRIVED: 'arrived',

    /**
     * TODO: Write general description for this element
     */
    FULFILLED: 'fulfilled',

    /**
     * TODO: Write general description for this element
     */
    CANCELLED: 'cancelled',

    /**
     * TODO: Write general description for this element
     */
    NOSHOW: 'noshow',

};

module.exports = StatusEnum312Enum;
