/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const StatusEnum644Enum = {

    /**
     * TODO: Write general description for this element
     */
    REGISTERED: 'registered',

    /**
     * TODO: Write general description for this element
     */
    PRELIMINARY: 'preliminary',

    /**
     * TODO: Write general description for this element
     */
    ENUM_FINAL: 'final',

    /**
     * TODO: Write general description for this element
     */
    AMMENDED: 'ammended',

    /**
     * TODO: Write general description for this element
     */
    CANCELLED: 'cancelled',

    /**
     * TODO: Write general description for this element
     */
    ENTEREDINERROR: 'entered-in-error',

    /**
     * TODO: Write general description for this element
     */
    UNKNOWN: 'unknown',

};

module.exports = StatusEnum644Enum;
