/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const SummaryEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_TRUE: 'true',

    /**
     * TODO: Write general description for this element
     */
    ENUM_FALSE: 'false',

    /**
     * TODO: Write general description for this element
     */
    TEXT: 'text',

    /**
     * TODO: Write general description for this element
     */
    DATA: 'data',

};

module.exports = SummaryEnum;
