/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const SystemEnum = {

    /**
     * TODO: Write general description for this element
     */
    PHONE: 'phone',

    /**
     * TODO: Write general description for this element
     */
    FAX: 'fax',

    /**
     * TODO: Write general description for this element
     */
    EMAIL: 'email',

    /**
     * TODO: Write general description for this element
     */
    PAGER: 'pager',

    /**
     * TODO: Write general description for this element
     */
    OTHER: 'other',

};

module.exports = SystemEnum;
