/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TargetItemEnum = {

    /**
     * TODO: Write general description for this element
     */
    MISSING: 'missing',

    /**
     * TODO: Write general description for this element
     */
    EXACT: 'exact',

    /**
     * TODO: Write general description for this element
     */
    CONTAINS: 'contains',

    /**
     * TODO: Write general description for this element
     */
    NOT: 'not',

    /**
     * TODO: Write general description for this element
     */
    TEXT: 'text',

    /**
     * TODO: Write general description for this element
     */
    ENUM_IN: 'in',

    /**
     * TODO: Write general description for this element
     */
    NOTIN: 'not-in',

    /**
     * TODO: Write general description for this element
     */
    BELOW: 'below',

    /**
     * TODO: Write general description for this element
     */
    ABOVE: 'above',

    /**
     * TODO: Write general description for this element
     */
    TYPE: 'type',

};

module.exports = TargetItemEnum;
