/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Element = require('./Element');

/**
 * Creates an instance of Timing
 */
class Timing extends Element {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.event = this.constructor.getValue(obj.event);
        this.repeat = this.constructor.getValue(obj.repeat);
        this.code = this.constructor.getValue(obj.code);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'event',
                realName: 'event',
                array: true,
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            { name: 'repeat', realName: 'repeat', type: 'Repeat' },
            { name: 'code', realName: 'code', type: 'CodeableConcept' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = Timing;
