/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TransactionModeEnum = {

    /**
     * TODO: Write general description for this element
     */
    NOTSUPPORTED: 'not-supported',

    /**
     * TODO: Write general description for this element
     */
    BATCH: 'batch',

    /**
     * TODO: Write general description for this element
     */
    TRANSACTION: 'transaction',

    /**
     * TODO: Write general description for this element
     */
    BOTH: 'both',

};

module.exports = TransactionModeEnum;
