/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TypeEnum709Enum = {

    /**
     * TODO: Write general description for this element
     */
    HASMEMBER: 'has-member',

    /**
     * TODO: Write general description for this element
     */
    DERIVEDFROM: 'derived-from',

    /**
     * TODO: Write general description for this element
     */
    SEQUELTO: 'sequel-to',

    /**
     * TODO: Write general description for this element
     */
    REPLACES: 'replaces',

    /**
     * TODO: Write general description for this element
     */
    QUALIFIEDBY: 'qualified-by',

    /**
     * TODO: Write general description for this element
     */
    INTERFEREDBY: 'interfered-by',

};

module.exports = TypeEnum709Enum;
