/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    POSTAL: 'postal',

    /**
     * TODO: Write general description for this element
     */
    PHYSICAL: 'physical',

    /**
     * TODO: Write general description for this element
     */
    BOTH: 'both',

};

module.exports = TypeEnum;
