/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TypeEnum1640Enum = {

    /**
     * TODO: Write general description for this element
     */
    DOCUMENT: 'document',

    /**
     * TODO: Write general description for this element
     */
    MESSAGE: 'message',

    /**
     * TODO: Write general description for this element
     */
    TRANSACTION: 'transaction',

    /**
     * TODO: Write general description for this element
     */
    TRANSACTIONRESPONSE: 'transaction-response',

    /**
     * TODO: Write general description for this element
     */
    BATCH: 'batch',

    /**
     * TODO: Write general description for this element
     */
    BATCHRESPONSE: 'batch-response',

    /**
     * TODO: Write general description for this element
     */
    HISTORY: 'history',

    /**
     * TODO: Write general description for this element
     */
    SEARCHSET: 'searchset',

    /**
     * TODO: Write general description for this element
     */
    COLLECTION: 'collection',

};

module.exports = TypeEnum1640Enum;
