/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TypeEnum125Enum = {

    /**
     * TODO: Write general description for this element
     */
    NUMBER: 'number',

    /**
     * TODO: Write general description for this element
     */
    DATE: 'date',

    /**
     * TODO: Write general description for this element
     */
    ENUM_STRING: 'string',

    /**
     * TODO: Write general description for this element
     */
    TOKEN: 'token',

    /**
     * TODO: Write general description for this element
     */
    REFERENCE: 'reference',

    /**
     * TODO: Write general description for this element
     */
    COMPOSITE: 'composite',

    /**
     * TODO: Write general description for this element
     */
    QUANTITY: 'quantity',

    /**
     * TODO: Write general description for this element
     */
    URI: 'uri',

};

module.exports = TypeEnum125Enum;
