/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TypeEnum381Enum = {

    /**
     * TODO: Write general description for this element
     */
    ALLERGY: 'allergy',

    /**
     * TODO: Write general description for this element
     */
    INTOLERANCE: 'intolerance',

};

module.exports = TypeEnum381Enum;
