/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TypeEnum874Enum = {

    /**
     * TODO: Write general description for this element
     */
    REPLACE: 'replace',

    /**
     * TODO: Write general description for this element
     */
    REFER: 'refer',

    /**
     * TODO: Write general description for this element
     */
    SEEALSO: 'seealso',

};

module.exports = TypeEnum874Enum;
