/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const UseEnum191Enum = {

    /**
     * TODO: Write general description for this element
     */
    USUAL: 'usual',

    /**
     * TODO: Write general description for this element
     */
    OFFICIAL: 'official',

    /**
     * TODO: Write general description for this element
     */
    TEMP: 'temp',

    /**
     * TODO: Write general description for this element
     */
    NICKNAME: 'nickname',

    /**
     * TODO: Write general description for this element
     */
    ANONYMOUS: 'anonymous',

    /**
     * TODO: Write general description for this element
     */
    OLD: 'old',

    /**
     * TODO: Write general description for this element
     */
    MAIDEN: 'maiden',

};

module.exports = UseEnum191Enum;
