/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const UseEnum = {

    /**
     * TODO: Write general description for this element
     */
    HOME: 'home',

    /**
     * TODO: Write general description for this element
     */
    WORK: 'work',

    /**
     * TODO: Write general description for this element
     */
    TEMP: 'temp',

    /**
     * TODO: Write general description for this element
     */
    OLD: 'old',

};

module.exports = UseEnum;
