/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const VerificationStatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    PROVISIONAL: 'provisional',

    /**
     * TODO: Write general description for this element
     */
    DIFFERENTIAL: 'differential',

    /**
     * TODO: Write general description for this element
     */
    CONFIRMED: 'confirmed',

    /**
     * TODO: Write general description for this element
     */
    REFUTED: 'refuted',

    /**
     * TODO: Write general description for this element
     */
    ENTEREDINERROR: 'entered-in-error',

    /**
     * TODO: Write general description for this element
     */
    UNKNOWN: 'unknown',

};

module.exports = VerificationStatusEnum;
