/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const VersioningEnum = {

    /**
     * TODO: Write general description for this element
     */
    NOVERSION: 'no-version',

    /**
     * TODO: Write general description for this element
     */
    VERSIONED: 'versioned',

    /**
     * TODO: Write general description for this element
     */
    VERSIONEDUPDATE: 'versioned-update',

};

module.exports = VersioningEnum;
