/**
 * HospitalRunFHIRAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const WhenEnum = {

    /**
     * TODO: Write general description for this element
     */
    HS: 'HS',

    /**
     * TODO: Write general description for this element
     */
    WAKE: 'WAKE',

    /**
     * TODO: Write general description for this element
     */
    C: 'C',

    /**
     * TODO: Write general description for this element
     */
    CM: 'CM',

    /**
     * TODO: Write general description for this element
     */
    CD: 'CD',

    /**
     * TODO: Write general description for this element
     */
    CV: 'CV',

    /**
     * TODO: Write general description for this element
     */
    AC: 'AC',

    /**
     * TODO: Write general description for this element
     */
    ACM: 'ACM',

    /**
     * TODO: Write general description for this element
     */
    ACD: 'ACD',

    /**
     * TODO: Write general description for this element
     */
    ACV: 'ACV',

    /**
     * TODO: Write general description for this element
     */
    PC: 'PC',

    /**
     * TODO: Write general description for this element
     */
    PCM: 'PCM',

    /**
     * TODO: Write general description for this element
     */
    PCD: 'PCD',

    /**
     * TODO: Write general description for this element
     */
    PCV: 'PCV',

};

module.exports = WhenEnum;
